module.exports = {
    AUTO_VIEW_STATUS: 'true',
    AUTO_LIKE_STATUS: 'true',
    AUTO_RECORDING: 'true',
    AUTO_LIKE_EMOJI: ['🧩', '🍉', '💜', '🌸', '🪴', '💊', '💫', '🍂', '🌟', '🎋', '😶‍🌫️', '🫀', '🧿', '👀', '😘', '🚩', '🥰', '🗿', '💜', '💙', '🌝', '🖤', '💗'],
    PREFIX: '.',
    MAX_RETRIES: 3,
    GROUP_INVITE_LINK: 'https://chat.whatsapp.com/BAE3fB7V8Df203xfITReuu?mode=ac_t',
    ADMIN_LIST_PATH: './admin.json',
    IMAGE_PATH: 'https://i.postimg.cc/prxSKBm9/5798485336463100758-120.jpg',
    NEWSLETTER_JID: '120363420646690174@newsletter',
    NEWSLETTER_MESSAGE_ID: '428',
    OTP_EXPIRY: 300000,
    NEWS_JSON_URL: '',
    BOT_NAME: 'ᴊꜰx ᴍᴅ-x ᴍɪɴɪ',
    OWNER_NAME: 'ᴊᴇᴘʜᴛᴇʀ ᴛᴇᴄʜ',
    OWNER_NUMBER: '2349046157539',
    BOT_VERSION: '1.0.0',
    BOT_FOOTER: '> © ᴘᴏᴡᴇʀᴇᴅ ʙʏ ᴊᴇᴘʜᴛᴇʀ ᴛᴇᴄʜ',
    CHANNEL_LINK: 'https://whatsapp.com/channel/0029VbAxkJl0lwgqAOojKI3R',
};
